### ISSUE TITLE
Use Window events to update the app name

### ISSUE THREAD

**Issue by fapdash** [talonvoice/beta#28]
Some application set the application name late, so talon doesn't pick the name up.
Use Window events to update the app name after launch.

**Comment by lunixbochs** [comment]
should be fixed in the new 1064 release, please confirm

**Comment by fapdash** [comment]
Still an issue: `Window(app=App(pid=29736, "Java"), title="egit - org.eclipse.egit.core/src/org/eclipse/egit/core/op/CommitOperation.java - Eclipse SDK ")`
After talon restart: `Window(app=App(pid=29736, "Eclipse"), title="egit - org.eclipse.egit.core/src/org/eclipse/egit/core/op/CommitOperation.java - Eclipse SDK ")`

**Comment by lunixbochs** [comment]
should be fixed even better in 1066

**Comment by fapdash** [comment]
fixed. thank you!
